baseURL: https://forlag.nitwit.se
languageCode: sv
title: Nitwit Förlag
theme: hugo-refresh
# theme: ../..


#########################################
######## Uncomment this option ##########
#########################################
# This options specify where to look for the images used in this config
# The default value is the "asset" directory of this theme
# assetDir: "static"

# Option to specify the default language of the theme
# I.e., the landing language of your root 
DefaultContentLanguage: sv
IsMultiLingual: true
defaultContentLanguageInSubdir: false
## Option to disable additional language in your site.
disableLanguages: ["en"]

disableKinds: ["sitemap","RSS"]


Taxonomies:
  tag: "tags"

# Supported fonts are:
# https://fonts.google.com/

# Icons taken from:
# https://konpa.github.io/devicon/
# https://bulkitv2.cssninja.io/_components-icons-fa.html

params:
  # parameter used to specify the number of article in each row 
  # for the summary pages, the possible options are: 2, 3, 4, 5 or 6
  articlesPerRow: 3 

  # option to specify the favicon image of the site
  # the path is relative to the folder "assetDir" of this configuration
  favicon: "/images/favicon.svg"

  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: false
  # parameter used to specify if you want to calculate the css integrity
  cssIntegrity: true
  # parameter used to specify if you want to calculate the js integrity
  jsIntegrity: true
  # option to specify the main colour of the theme
  mainColour: "#f2a746"

  # summary options
  summary:
    # option to specify the default image in the summary list
    # the starting folder is configure in "assetDir" of this file
    defaultImage : "/images/default_summary.jpg"
  
  # loading options
  loading:
    # option to specify the loading image
    # the starting folder is configure in "assetDir" of this file
    image: "/images/loaders/rings.svg"

  # main pages options
  mainPage:
    # option to specify the main font of the theme
    fontFamily: "Open Sans" 

  # sidebar options
  sidebar:
    # option to specify the logo of the sidebar
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/refresh-square.svg"
    # option to specify the font of the sidebar
    fontFamily: "Open Sans" # "Open Sans"

  # navbar options
  navbar:
    # option to specify the font used in the navbar
    fontFamily: "Open Sans"
    # option to show the little logos on the side of the navbar items
    showIcons: true
    
  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    # the starting folder is configure in "assetDir" of this file
    image: "/images/avataaars_404.png"
    # option to specify the title of the 404 page
    title: 404 Page Not Found :(
    # option to specify the subtitle of the 404 page
    subtitle: This is not the page you were looking for...
    # option to specify the width of the image in the 404 page
    imageWidth: 500px

  # homepage options
  homepage:
    # this options let you specify if you want a link to the homepage
    # it can be: "none", "menu", "footer" or "menu+footer"
    # linkPosition: "footer" 
    # this options let you specify the text of the link to the homepage
    # linkText: "Homepage"  
    # option to specify the title in the homepage
    title: Nitwit Förlag
    # option to specify the subtitle in the homepage
    subtitle: Vi är ett litet förlag med begränsad utgivning och fokus på skönlitteratur.
    # option to specify image in the homepage
    image: "/images/background_texture_white2.png" # worker.svg 
    # option to specify the width of the image in the homepage
    imageWidth: 515px


  # footer options
  footer:
    # option to specify the logo in the footer
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/Dragonfly_Square.png"
    # option to specify your contact email in the footer
    email: 
      link: info@nitwit.se
      title: Email
    facebook: 
      link: nitwit.se
      title: Facebook 
    # option to specify your linkedin profile in the footer
    linkedin: 
      link: company/nitwit-ab
      title: LinkedIn

    copyright: Nitwit AB 2023

###################################################################
################## multilanguage support options ##################
###################################################################
languages:
  sv:
    languageName:       Swedish
    weight:             1
  en:
    languageName:       English
    weight:             2
    # When Specifying different parameters for a different language 
    # you need to specify all the mandatory sub-parameters as well.
    # E.g.: if you specify the "homepage" parameter then you need to
    #       specify all mandatory sub-parameters, e.g.: "title". 
    # See example below:
    params:
      homepage:
        title: Nitwit Publishing
        subtitle: Boutique publisher, specialising in Swedish literature
        image: "/images/dragonfly_logo.png" # worker.svg 
        imageWidth: 250px
      
      # Some sub-parameters of the "footer" parameter
      # can be omitted because the code allows for them to be 
      # missed but they will treated as they do not exist,
      # i.e., the parameters of the default language
      # won't be inherited.
      footer:
        logo: "/images/Dragonfly_Square.png"
        email: 
          link: info@nitwit.se
          title: Email
        facebook: 
          link: nitwit.se
          title: Facebook 
        # option to specify your linkedin profile in the footer
        linkedin: 
          link: company/nitwit-ab
          title: LinkedIn

        copyright: Nitwit AB 2023
      

markup:
  goldmark:
    renderer:
      unsafe: true
